spring:
  application:
    name: monitoring-dashboard-api
  
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m

server:
  port: 8080
  compression:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Configuration BigTable
bigtable:
  project-id: gu1-top20-iacc
  instance-id: transaction-logs
  tables:
    metrics: metrics_log
    logs: raw_log
    processing: processing_log
  column-families:
    metrics: cf1
    logs: log
    processing-message: message
    processing-log: log

# Configuration Monitoring
monitoring:
  project-id: eme-iacc1
  uptime-checks:
    pi-gateway: gateway-log-check-iENy3kUv_MY
    pi-connector: pi-connector-log-check-72FI4qEwdK8

# CORS Configuration
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:5173
    - https://your-frontend-domain.com
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  max-age: 3600

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha